#!/usr/bin/env python3
"""
Coupled per-civilisation compartmental ODE model with PI-driven inflow.

For each civilisation we track the same six compartments as ode_model.py:
  D, A, H_D, H_A, P_D, P_A

Here the domestic early-career inflow is endogenous:
    I(P_D) = I0 + r * P_D
where
  I0  : exogenous baseline inflow (new PhDs/postdocs not generated by current PIs)
  r   : PI reproduction rate (new domestic entrants produced per PI per year)

Because an unrestricted linear PI feedback is explosive (r is larger than the
PI dropout rate d for any realistic cross-sectional reproduction ratio), we cap
r at the largest value that keeps the linearised 6x6 system stable
(half of the r at which the leading eigenvalue crosses zero).  This is a
conservative, transparent parameterisation; a saturating recruitment function
would be required for a fully structural calibration.

Usage:
    python src/ode_model_endogenous.py
"""

import argparse
import json
import os
from collections import defaultdict
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.linalg import solve, eigvals


BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = BASE_DIR / "data"
COHORT_DIR = Path(os.environ.get("RESEARCHER_MOBILITY_COHORT_DIR", str(DATA_DIR / "cohort")))
RESULTS_DIR = Path(os.environ.get("RESEARCHER_MOBILITY_RESULTS_DIR", str(BASE_DIR / "results" / "endogenous")))

COMPARTMENTS = ["D", "A", "H_D", "H_A", "P_D", "P_A"]
RATE_NAMES = ["alpha", "beta", "h_D", "h_A", "p_D", "p_A", "d"]


def load_group_mapping():
    with open(DATA_DIR / "country_civilization_mapping.json", "r", encoding="utf-8") as f:
        mapping = json.load(f)
    a2g = {}
    for a3, info in mapping.items():
        a2 = info.get("alpha_2")
        g = info.get("group")
        if a2 and g:
            a2g[a2] = g
    return a2g


def work_groups(work, a2g):
    """Return the set of civilisation groups appearing on a work."""
    groups = set()
    for auth in work.get("authorships", []):
        for inst in auth.get("institutions", []):
            cc = inst.get("country_code")
            if cc in a2g:
                groups.add(a2g[cc])
    return groups


def last_author_ids(work):
    """Return the author id(s) whose position is 'last' on this work."""
    ids = []
    for auth in work.get("authorships", []):
        if auth.get("author_position") == "last":
            raw = (auth.get("author") or {}).get("id")
            if raw:
                ids.append(raw.split("/")[-1])
    return ids


def n_authors(work):
    return len(work.get("authorships", []))


def compute_coauthor_stats(a2g, recent_years=(2020, 2021, 2022, 2023)):
    """
    From the cached stratified work sample, compute for each civilisation:
      - mean_authors : mean number of authors per AI/ML work
      - k_groups     : median number of distinct last-author groups per recent year
    """
    sample_file = COHORT_DIR / "raw_sampled_works.json"
    if not sample_file.exists():
        raise FileNotFoundError(f"Sample cache not found: {sample_file}. Run cohort_extraction.py first.")

    with open(sample_file, "r", encoding="utf-8") as f:
        works = json.load(f)

    group_works = defaultdict(list)
    for w in works:
        y = w.get("publication_year")
        for g in work_groups(w, a2g):
            group_works[g].append((w, y))

    stats = {}
    for g, items in group_works.items():
        n_auth_counts = [n_authors(w) for w, _ in items]
        c_bar = float(np.mean(n_auth_counts)) if n_auth_counts else np.nan

        yearly_last = defaultdict(set)
        for w, y in items:
            if y in recent_years:
                for lid in last_author_ids(w):
                    yearly_last[y].add(lid)
        yearly_counts = [len(yearly_last[y]) for y in recent_years if y in yearly_last]
        if not yearly_counts:
            yearly_last = defaultdict(set)
            for w, y in items:
                for lid in last_author_ids(w):
                    yearly_last[y].add(lid)
            yearly_counts = [len(s) for s in yearly_last.values()]
        k_groups = int(np.median(yearly_counts)) if yearly_counts else 10

        stats[g] = {
            "mean_authors": c_bar,
            "k_groups": k_groups,
            "n_sampled_works": len(items),
            "recent_last_author_counts": yearly_counts,
        }
    return stats


def estimate_inflows(cohort, start_year=2000, end_year=2016):
    """Annual new domestic entrants per group from observed career starts."""
    df = cohort[(cohort["career_start"] >= start_year) & (cohort["career_start"] <= end_year)]
    counts = (df.groupby(["origin_group", "career_start"])
                .size()
                .unstack(fill_value=0)
                .reindex(columns=range(start_year, end_year + 1), fill_value=0))
    annual_mean = counts.mean(axis=1)
    annual_mean = annual_mean.replace([np.inf, -np.inf], np.nan).fillna(0)
    return annual_mean.to_dict()


def build_matrix(params):
    """
    Build the 6x6 transition matrix M for a single civilisation with
    PI-driven inflow term M[0,4] = r.
    """
    alpha = params["alpha"]
    beta = params["beta"]
    h_D = params["h_D"]
    h_A = params["h_A"]
    p_D = params["p_D"]
    p_A = params["p_A"]
    d = params["d"]
    r = params.get("r", 0.0)

    M = np.zeros((6, 6))
    # D row: loss to abroad, hit, dropout; gain from return; PI-driven inflow
    M[0, 0] = -(alpha + h_D + d)
    M[0, 1] = beta
    M[0, 4] = r
    # A row
    M[1, 0] = alpha
    M[1, 1] = -(h_A + beta + d)
    # H_D row
    M[2, 0] = h_D
    M[2, 2] = -(p_D + d)
    M[2, 3] = beta
    # H_A row
    M[3, 1] = h_A
    M[3, 3] = -(p_A + beta + d)
    # P_D row
    M[4, 2] = p_D
    M[4, 4] = -d
    M[4, 5] = beta
    # P_A row
    M[5, 3] = p_A
    M[5, 5] = -(beta + d)
    return M


def r_critical(params, r_max=0.5, n_iter=40):
    """
    Find the largest r for which the linear system dy/dt = M(r) y is stable
    (all eigenvalues have negative real parts).  Use bisection.
    """
    lo, hi = 0.0, r_max
    for _ in range(n_iter):
        mid = (lo + hi) / 2.0
        M = build_matrix({**params, "r": mid})
        if max(eigvals(M).real) > 0:
            hi = mid
        else:
            lo = mid
    return lo


def estimate_endogenous_inflow(cohort, rates, safety_factor=0.5,
                                career_start_min=2000, career_start_max=2016):
    """
    Estimate I0 and r for each civilisation.

    r is capped at safety_factor * r_critical to keep the linear ODE stable.
    The observed cross-sectional reproduction ratio I/P_D is unstable in the
    linear model (it exceeds r_critical), so we report it for reference but
    use the stability-capped value.
    """
    inflows = estimate_inflows(cohort, career_start_min, career_start_max)
    pi_counts = cohort[cohort["pi"] == True].groupby("origin_group").size().to_dict()

    I0_dict = {}
    r_dict = {}
    rcrit_dict = {}
    r_obs_dict = {}

    for group, row in rates.iterrows():
        params = {c: float(row[c]) for c in RATE_NAMES}
        I = inflows.get(group, 0.0)
        P_D_obs = pi_counts.get(group, 0)

        rcrit = r_critical(params)
        r_cap = safety_factor * rcrit

        if P_D_obs > 0 and I > 0:
            r_obs = I / P_D_obs
        else:
            r_obs = 0.0

        r_use = min(r_obs, r_cap) if r_obs > 0 else r_cap
        I0 = max(0.0, I - r_use * P_D_obs)

        I0_dict[group] = I0
        r_dict[group] = r_use
        rcrit_dict[group] = rcrit
        r_obs_dict[group] = r_obs

    return I0_dict, r_dict, rcrit_dict, r_obs_dict


def _linear_equilibrium(M, I0):
    """Solve M y_eq + b = 0 with b[0] = -I0."""
    b = np.zeros(6)
    b[0] = -I0
    y_eq = solve(M, b, assume_a="gen")
    T = y_eq[0] + y_eq[2] + y_eq[4]
    return y_eq, T


def saturating_equilibrium(params, I0):
    """
    Equilibrium for I(P_D) = I0 + r * P_D / (1 + epsilon * P_D).

    The state dynamics are linear except for the first-equation inflow, so
    once P_D is known the equilibrium is y_eq = -A^{-1} [I(P_D), 0, ...]^T,
    where A is the baseline matrix (r feedback removed).
    """
    r = params.get("r", 0.0)
    epsilon = params.get("epsilon", 0.0)
    p_idx = COMPARTMENTS.index("P_D")

    # Baseline transition matrix without PI-driven linear feedback
    p_no_r = {**params, "r": 0.0}
    A = build_matrix(p_no_r)
    A_inv = np.linalg.inv(A)
    g = -A_inv[p_idx, 0]

    if g <= 0 or (r <= 0 and I0 <= 0):
        return np.zeros(6), 0.0

    # Positive root of epsilon P^2 + (1 - g I0 epsilon - g r) P - g I0 = 0
    a = epsilon
    b_coef = 1.0 - g * I0 * epsilon - g * r
    c = -g * I0

    if abs(a) < 1e-12:
        P = -c / b_coef if abs(b_coef) > 1e-12 else 0.0
    else:
        disc = b_coef * b_coef - 4.0 * a * c
        sqrt_disc = np.sqrt(max(0.0, disc))
        # c < 0 guarantees one positive root with (-b + sqrt(disc)) / (2a)
        if abs(b_coef + sqrt_disc) > 1e-12:
            P = (-b_coef + sqrt_disc) / (2.0 * a)
        elif abs(b_coef - sqrt_disc) > 1e-12:
            P = (-b_coef - sqrt_disc) / (2.0 * a)
        else:
            P = 0.0
    P = max(0.0, P)

    I_star = I0 + r * P / (1.0 + epsilon * P)
    y_eq = -A_inv[:, 0] * I_star
    T = y_eq[0] + y_eq[2] + y_eq[4]
    return y_eq, T


def equilibrium(params, I0):
    """Solve M y_eq + b = 0 with b[0] = -I0; return vector and T."""
    epsilon = params.get("epsilon", 0.0)
    if epsilon and epsilon > 0:
        return saturating_equilibrium(params, I0)
    M = build_matrix(params)
    return _linear_equilibrium(M, I0)


def compartment_value(y_eq, name):
    """Return a compartment value or named aggregate."""
    if name == "T":
        return y_eq[0] + y_eq[2] + y_eq[4]
    if name == "P":
        return y_eq[4]
    return y_eq[COMPARTMENTS.index(name)]


def sensitivity_table(params, I0, target="T", delta=0.01):
    """
    Compute the elasticity of the equilibrium target with respect to each
    transition rate, r, and the exogenous baseline I0.
    """
    y0, _ = equilibrium(params, I0)
    base = compartment_value(y0, target)
    rows = []
    rates_to_test = list(params.keys()) + ["I0"]
    for rate_name in rates_to_test:
        if rate_name == "I0":
            I0_2 = I0 * (1 + delta)
            y2, _ = equilibrium(params, I0_2)
        else:
            p2 = dict(params)
            p2[rate_name] = params[rate_name] * (1 + delta)
            y2, _ = equilibrium(p2, I0)
        val2 = compartment_value(y2, target)
        elasticity = ((val2 - base) / base) / delta if base != 0 and delta != 0 else np.nan
        current = I0 if rate_name == "I0" else params[rate_name]
        rows.append({
            "rate": rate_name,
            "value": current,
            "target_value_after_1pct_change": val2,
            "elasticity": elasticity,
        })
    return pd.DataFrame(rows).sort_values("elasticity", ascending=False)


def point_of_no_return(params, I0, M_threshold, rate_name, target="T",
                       min_factor=0.001, max_factor=20.0, n_points=2000):
    """
    Find the multiplicative factor at which the equilibrium target equals
    M_threshold.  Works for transition rates, r, and I0.
    """
    if rate_name == "I0":
        current = I0
    else:
        current = params[rate_name]

    if current <= 0:
        test_values = np.linspace(0.0, max_factor * 0.05, n_points)
    else:
        test_values = current * np.linspace(min_factor, max_factor, n_points)
    test_values = np.unique(np.maximum(test_values, 1e-12))

    def target_at(v):
        if rate_name == "I0":
            y, _ = equilibrium(params, v)
        else:
            p2 = dict(params)
            p2[rate_name] = v
            y, _ = equilibrium(p2, I0)
        return compartment_value(y, target)

    # Determine monotonic direction locally to avoid artefacts from
    # near-singular behaviour at extreme rate values.
    current_T = target_at(current)
    T_plus = target_at(current * (1 + 0.01))
    if T_plus > current_T:
        direction = +1
    elif T_plus < current_T:
        direction = -1
    else:
        direction = 0

    Ts = np.array([target_at(v) for v in test_values])
    diff = Ts - M_threshold

    if current_T <= M_threshold:
        return {
            "rate_name": rate_name,
            "current_rate": current,
            "critical_factor": np.nan,
            "critical_rate": np.nan,
            "T_at_critical": current_T,
            "is_within_bounds": False,
            "direction": direction,
            "note": "already_below_threshold",
        }

    if direction == 0:
        return {
            "rate_name": rate_name,
            "current_rate": current,
            "critical_factor": np.nan,
            "critical_rate": np.nan,
            "T_at_critical": current_T,
            "is_within_bounds": False,
            "direction": 0,
            "note": "no_effect",
        }

    current_factor = 1.0
    factor_values = test_values / current if current > 0 else np.linspace(0, max_factor, n_points)
    if direction == -1:
        idx_mask = factor_values >= current_factor
        scan_factors = factor_values[idx_mask]
        scan_diff = diff[idx_mask]
    else:
        idx_mask = factor_values <= current_factor
        scan_factors = factor_values[idx_mask][::-1]
        scan_diff = diff[idx_mask][::-1]

    crossings = np.where(np.diff(np.sign(scan_diff)))[0]
    if len(crossings) == 0:
        last_factor = float(scan_factors[-1])
        last_rate = last_factor * current if current > 0 else last_factor
        return {
            "rate_name": rate_name,
            "current_rate": current,
            "critical_factor": last_factor,
            "critical_rate": last_rate,
            "T_at_critical": target_at(last_rate),
            "is_within_bounds": False,
            "direction": direction,
            "note": "no_crossing_in_scanned_range",
        }

    idx = crossings[0]
    f0, f1 = scan_factors[idx], scan_factors[idx + 1]
    t0, t1 = scan_diff[idx] + M_threshold, scan_diff[idx + 1] + M_threshold
    frac = (M_threshold - t0) / (t1 - t0) if t1 != t0 else 0.0
    critical_factor = f0 + frac * (f1 - f0)
    critical_rate = critical_factor * current if current > 0 else critical_factor
    return {
        "rate_name": rate_name,
        "current_rate": current,
        "critical_factor": critical_factor,
        "critical_rate": critical_rate,
        "T_at_critical": M_threshold,
        "is_within_bounds": True,
        "direction": direction,
        "note": "crossing_found",
    }


def run_endogenous_model(k_override=None, save=True, scan_targets=("T", "P"),
                         safety_factor=0.5, cohort_df=None, rates_df=None,
                         saturating=False, saturation_k_factor=5.0,
                         use_observed_r=False, a2g=None, stats=None,
                         compute_sensitivity=True, compute_pnr=True,
                         career_start_min=2000, career_start_max=2016):
    a2g = a2g if a2g is not None else load_group_mapping()
    if stats is None:
        stats = compute_coauthor_stats(a2g)

    cohort = cohort_df if cohort_df is not None else pd.read_csv(COHORT_DIR / "cohort.csv")
    rates = rates_df if rates_df is not None else pd.read_csv(
        COHORT_DIR / "transition_rates.csv"
    ).set_index("group")

    I0_dict, r_dict, rcrit_dict, r_obs_dict = estimate_endogenous_inflow(
        cohort, rates, safety_factor=safety_factor,
        career_start_min=career_start_min, career_start_max=career_start_max,
    )

    inflows = estimate_inflows(cohort, career_start_min, career_start_max)
    pi_counts = cohort[cohort["pi"] == True].groupby("origin_group").size().to_dict()

    rate_cols = RATE_NAMES.copy()
    summary_rows = []
    sensitivity_frames = []
    pnr_frames = []

    for group, row in rates.iterrows():
        params = {c: float(row[c]) for c in rate_cols}
        I0 = I0_dict.get(group, 0.0)
        r = r_dict.get(group, 0.0)

        if saturating:
            r = r_obs_dict.get(group, 0.0) if use_observed_r else r
            P_D_obs = pi_counts.get(group, 0)
            I_total = inflows.get(group, 0.0)
            if P_D_obs > 0 and r > 0:
                K = max(P_D_obs, saturation_k_factor * P_D_obs)
                epsilon = 1.0 / K
                I0 = max(0.0, I_total - r * P_D_obs / (1.0 + epsilon * P_D_obs))
                params["epsilon"] = epsilon
            else:
                params["epsilon"] = 0.0

        if I0 <= 0 or np.isnan(I0):
            continue

        params["r"] = r

        st = stats.get(group, {})
        c_bar = st.get("mean_authors", np.nan)
        k_obs = st.get("k_groups", 0)
        if isinstance(k_override, dict):
            k = k_override.get(group, k_obs)
        else:
            k = k_override if k_override is not None else k_obs
        M_threshold = k * c_bar if not (np.isnan(c_bar) or c_bar == 0) else np.nan

        y_eq, T_eq = equilibrium(params, I0)
        P_eq = y_eq[4]

        summary_rows.append({
            "group": group,
            "I0": I0,
            "r": r,
            "epsilon": params.get("epsilon", 0.0),
            "r_obs": r_obs_dict.get(group, np.nan),
            "r_critical": rcrit_dict.get(group, np.nan),
            "c_bar": c_bar,
            "k_groups_observed": k_obs,
            "k_used": k,
            "M_threshold": M_threshold,
            "T_equilibrium": T_eq,
            "D_eq": y_eq[0],
            "A_eq": y_eq[1],
            "H_D_eq": y_eq[2],
            "H_A_eq": y_eq[3],
            "P_D_eq": y_eq[4],
            "P_A_eq": y_eq[5],
            "margin_to_threshold_T": T_eq - M_threshold,
            "P_D_equilibrium": P_eq,
        })

        for target in scan_targets:
            if not compute_sensitivity and not compute_pnr:
                continue
            target_label = {"T": "domestic_active", "P": "domestic_PIs"}.get(target, target)
            if compute_sensitivity:
                sens = sensitivity_table(params, I0, target=target)
                sens["group"] = group
                sens["target"] = target_label
                sens["M_threshold"] = M_threshold
                sensitivity_frames.append(sens)

            if compute_pnr:
                for rate_name in list(params.keys()) + ["I0"]:
                    if rate_name != "I0" and params[rate_name] <= 0:
                        continue
                    pnr = point_of_no_return(params, I0, M_threshold, rate_name, target=target)
                    pnr["group"] = group
                    pnr["target"] = target_label
                    pnr["T_equilibrium"] = T_eq
                    pnr["M_threshold"] = M_threshold
                    pnr_frames.append(pnr)

    summary_df = pd.DataFrame(summary_rows)
    sens_df = pd.concat(sensitivity_frames, ignore_index=True) if sensitivity_frames else pd.DataFrame()
    pnr_df = pd.DataFrame(pnr_frames) if pnr_frames else pd.DataFrame()

    if save:
        RESULTS_DIR.mkdir(parents=True, exist_ok=True)
        summary_df.to_csv(RESULTS_DIR / "equilibrium_summary.csv", index=False, encoding="utf-8-sig")
        sens_df.to_csv(RESULTS_DIR / "sensitivity.csv", index=False, encoding="utf-8-sig")
        pnr_df.to_csv(RESULTS_DIR / "point_of_no_return.csv", index=False, encoding="utf-8-sig")

    return summary_df, sens_df, pnr_df


def summarize_results():
    """Generate human-readable intervention summary from endogenous results."""
    summary = pd.read_csv(RESULTS_DIR / "equilibrium_summary.csv")
    sens = pd.read_csv(RESULTS_DIR / "sensitivity.csv")
    pnr = pd.read_csv(RESULTS_DIR / "point_of_no_return.csv")

    INFLOW_RATES = ["I0", "r"]
    TRANSITIONS = ["alpha", "beta", "h_D", "h_A", "p_D", "p_A", "d"]

    def topn(df, target, rates, n=3):
        d = df[(df["target"] == target) & (df["rate"].isin(rates))].copy()
        d["abs_elasticity"] = d["elasticity"].abs()
        d = d.sort_values(["group", "abs_elasticity"], ascending=[True, False])
        return d.groupby("group").head(n)

    top_T_inflow = topn(sens, "domestic_active", INFLOW_RATES + ["d"], n=3)
    top_T_trans = topn(sens, "domestic_active", TRANSITIONS, n=3)
    top_P_inflow = topn(sens, "domestic_PIs", INFLOW_RATES + ["d"], n=3)
    top_P_trans = topn(sens, "domestic_PIs", TRANSITIONS, n=3)

    top_T_inflow.to_csv(RESULTS_DIR / "top_inflow_T.csv", index=False, encoding="utf-8-sig")
    top_T_trans.to_csv(RESULTS_DIR / "top_transitions_T.csv", index=False, encoding="utf-8-sig")
    top_P_inflow.to_csv(RESULTS_DIR / "top_inflow_P.csv", index=False, encoding="utf-8-sig")
    top_P_trans.to_csv(RESULTS_DIR / "top_transitions_P.csv", index=False, encoding="utf-8-sig")

    pnr2 = pnr[pnr["is_within_bounds"] == True].copy()
    pnr2["proximity"] = (pnr2["critical_factor"] - 1).abs()
    closest = pnr2.loc[pnr2.groupby(["group", "target"])["proximity"].idxmin()]
    closest.to_csv(RESULTS_DIR / "closest_point_of_no_return.csv", index=False, encoding="utf-8-sig")

    lines = ["# AI/ML 研究者流動：PI 駆動流入を追加した連立 ODE（パイロット）\n"]
    lines.append("## 平衡国内活動研究者数 T = D + H_D + P_D と最小存続閾値 M = k × c_bar\n")
    for _, row in summary.iterrows():
        lines.append(
            f"- **{row['group']}**: T_eq = {row['T_equilibrium']:.1f}, "
            f"M = {row['M_threshold']:.1f} (k={int(row['k_used'])}, c_bar={row['c_bar']:.2f}), "
            f"余裕 = {row['margin_to_threshold_T']:.1f}; "
            f"I0 = {row['I0']:.4f}, r = {row['r']:.5f} (r_obs = {row['r_obs']:.4f}, r_crit = {row['r_critical']:.5f})\n"
        )

    lines.append("\n## 国内活動研究者数に最も影響する要因（流入・ドロップアウト含む）\n")
    for g, df in top_T_inflow.groupby("group"):
        lines.append(f"\n### {g}\n")
        for _, r in df.iterrows():
            sign = "+" if r["elasticity"] > 0 else ""
            lines.append(
                f"- {r['rate']}: 弾力性 = {sign}{r['elasticity']:.4f} "
                f"（{r['rate']} を 1% 上げると T は {sign}{r['elasticity']:.2f}% 変化）\n"
            )

    lines.append("\n## 国内活動研究者数に最も影響する遷移係数（弾力性）\n")
    for g, df in top_T_trans.groupby("group"):
        lines.append(f"\n### {g}\n")
        for _, r in df.iterrows():
            sign = "+" if r["elasticity"] > 0 else ""
            lines.append(
                f"- {r['rate']}: 弾力性 = {sign}{r['elasticity']:.4f} "
                f"（{r['rate']} を 1% 上げると T は {sign}{r['elasticity']:.2f}% 変化）\n"
            )

    lines.append("\n## 国内 PI 数に最も影響する遷移係数（弾力性）\n")
    for g, df in top_P_trans.groupby("group"):
        lines.append(f"\n### {g}\n")
        for _, r in df.iterrows():
            sign = "+" if r["elasticity"] > 0 else ""
            lines.append(f"- {r['rate']}: 弾力性 = {sign}{r['elasticity']:.4f}\n")

    lines.append("\n## 各文明圏で最も近い point-of-no-return（T に対する係数変化率）\n")
    for _, r in closest[closest["target"] == "domestic_active"].iterrows():
        action = "増加" if r["direction"] == -1 else ("減少" if r["direction"] == 1 else "影響なし")
        lines.append(
            f"- **{r['group']}**: {r['rate_name']} を現在の {r['critical_factor']:.3f} 倍 "
            f"（{r['current_rate']:.5f} → {r['critical_rate']:.5f}）に{action}させると "
            f"T = M = {r['M_threshold']:.1f} に到達\n"
        )

    with open(RESULTS_DIR / "intervention_summary.md", "w", encoding="utf-8") as f:
        f.writelines(lines)

    print("Wrote summary to", RESULTS_DIR / "intervention_summary.md")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--data-dir", type=str, default=str(COHORT_DIR),
                        help="Directory containing cohort.csv, transition_rates.csv, and raw_sampled_works.json.")
    parser.add_argument("--results-dir", type=str, default=str(RESULTS_DIR),
                        help="Directory to write ODE results.")
    parser.add_argument("--k-override", type=int, default=None)
    parser.add_argument("--no-save", action="store_true")
    parser.add_argument("--safety-factor", type=float, default=0.5,
                        help="Fraction of r_critical used for the PI reproduction rate (default 0.5).")
    parser.add_argument("--saturating", action="store_true",
                        help="Use saturating inflow I(P_D) = I0 + r P_D / (1 + epsilon P_D).")
    parser.add_argument("--saturation-k-factor", type=float, default=5.0,
                        help="Factor on observed P_D used to define saturation capacity K (default 5.0).")
    parser.add_argument("--use-observed-r", action="store_true",
                        help="In saturating mode, use the uncapped observed r (still stable by saturation).")
    args = parser.parse_args()

    globals()["COHORT_DIR"] = Path(args.data_dir)
    globals()["RESULTS_DIR"] = Path(args.results_dir)

    summary_df, sens_df, pnr_df = run_endogenous_model(
        k_override=args.k_override,
        save=not args.no_save,
        safety_factor=args.safety_factor,
        saturating=args.saturating,
        saturation_k_factor=args.saturation_k_factor,
        use_observed_r=args.use_observed_r,
    )

    print("\n=== Endogenous inflow parameters ===")
    cols = ["group", "I0", "r", "r_obs", "r_critical"]
    if "epsilon" in summary_df.columns:
        cols.append("epsilon")
    print(summary_df[cols].to_string(index=False))

    print("\n=== Equilibrium domestic active pool T = D + H_D + P_D ===")
    print(summary_df[["group", "T_equilibrium", "M_threshold", "margin_to_threshold_T"]].to_string(index=False))

    print("\n=== Sensitivities (elasticity) ===")
    for (target, g), df in sens_df.groupby(["target", "group"]):
        print(f"\n--- target={target}, group={g} ---")
        print(df[["rate", "value", "elasticity"]].head(10).to_string(index=False))

    if not args.no_save:
        summarize_results()


if __name__ == "__main__":
    main()
